export interface Kino {
  name: string;
  ton: string;
  leinwand: string;
  projektion: string;
  plaetze: number;
  digital3D: boolean;
  image: string;
}

export const KINOS: Kino[] = [
  {
    name: "CINEMAGNUM",
    ton: "7.1 & Dolby Atmos",
    leinwand: "ca. 610 m²",
    projektion: "Sony Quad 4k",
    plaetze: 524,
    digital3D: true,
    image: "/assets/images/cinemagnum.jpg",
  },
  {
    name: "Kino 1",
    ton: "7.1 & Dolby Atmos",
    leinwand: "ca. 109 m²",
    projektion: "Digital Laser 4k",
    plaetze: 544,
    digital3D: true,
    image: "/assets/images/kino1.jpg",
  },
  {
    name: "Kino 2",
    ton: "7.1 & Dolby Atmos",
    leinwand: "ca. 82 m²",
    projektion: "Digital 4k",
    plaetze: 319,
    digital3D: true,
    image: "/assets/images/kino2.jpg",
  },
  {
    name: "Kino 3",
    ton: "7.1 & Dolby Atmos",
    leinwand: "ca. 109 m²",
    projektion: "Digital 4k",
    plaetze: 467,
    digital3D: true,
    image: "/assets/images/kino3.jpg",
  },
  {
    name: "Kino 4",
    ton: "7.1 & Dolby Atmos",
    leinwand: "ca. 72 m²",
    projektion: "Sony Dual 4K",
    plaetze: 317,
    digital3D: true,
    image: "/assets/images/kino4.jpg",
  },
  {
    name: "Kino 5",
    ton: "7.1 - Dirac Live",
    leinwand: "ca. 38 m²",
    projektion: "Digital 4k",
    plaetze: 208,
    digital3D: true,
    image: "/assets/images/kino5.jpg",
  },
  {
    name: "Kino 6",
    ton: "7.1 - Dirac Live",
    leinwand: "ca. 27 m²",
    projektion: "Digital 4k",
    plaetze: 105,
    digital3D: false,
    image: "/assets/images/kino6.jpg",
  },
  {
    name: "Kino 7",
    ton: "7.1 - Dirac Live",
    leinwand: "ca. 34 m²",
    projektion: "Digital 4k Sony",
    plaetze: 173,
    digital3D: false,
    image: "/assets/images/kino7.jpg",
  },
  {
    name: "Kino 8",
    ton: "7.1 - Dirac Live",
    leinwand: "ca. 27 m²",
    projektion: "Digital 4k",
    plaetze: 141,
    digital3D: false,
    image: "/assets/images/kino8.jpg",
  },
  {
    name: "Kino 9",
    ton: "7.1 - Dirac Live",
    leinwand: "ca. 27 m²",
    projektion: "Digital 4k",
    plaetze: 139,
    digital3D: false,
    image: "/assets/images/kino9.jpg",
  },
  {
    name: "Kino 10",
    ton: "7.1 & Dolby Atmos",
    leinwand: "ca. 38 m²",
    projektion: "Digital 4k",
    plaetze: 186,
    digital3D: true,
    image: "/assets/images/kino10.jpg",
  },
  {
    name: "CINECITTA' Deluxe 1",
    ton: "7.1 & Dolby Atmos",
    leinwand: "ca. 75 m²",
    projektion: "Sony Dual 4k",
    plaetze: 120,
    digital3D: true,
    image: "/assets/images/deluxe1.jpg",
  },
  {
    name: "CINECITTA' Deluxe 2",
    ton: "7.1 & Dolby Atmos",
    leinwand: "ca. 64 m²",
    projektion: "Digital 4k",
    plaetze: 105,
    digital3D: true,
    image: "/assets/images/deluxe2.jpg",
  },
  {
    name: "CINECITTA' Deluxe 3",
    ton: "7.1 & Dolby Atmos",
    leinwand: "ca. 34 m²",
    projektion: "Digital 4k",
    plaetze: 49,
    digital3D: true,
    image: "/assets/images/deluxe3.jpg",
  },
  {
    name: "CINECITTA' Deluxe 4",
    ton: "7.1 & Dolby Atmos",
    leinwand: "55 m²",
    projektion: "Samsung Onyx LED",
    plaetze: 63,
    digital3D: false,
    image: "/assets/images/deluxe4.jpg",
  },
  {
    name: "CINECITTA' Deluxe 5",
    ton: "7.1 & Dolby Atmos",
    leinwand: "17 m²",
    projektion: "DLP 4K Laser",
    plaetze: 31,
    digital3D: true,
    image: "/assets/images/deluxe5.jpg",
  },
  {
    name: "CINECITTA' Deluxe 6",
    ton: "7.1 & Dolby Atmos",
    leinwand: "ca. 50 m²",
    projektion: "Digital 4k",
    plaetze: 112,
    digital3D: false,
    image: "/assets/images/deluxe6.jpg",
  },
  {
    name: "CINECITTA' Deluxe 7",
    ton: "7.1 & Dolby Atmos",
    leinwand: "ca. 38 m²",
    projektion: "Digital 4k",
    plaetze: 60,
    digital3D: false,
    image: "/assets/images/deluxe7.jpg",
  },
  {
    name: "CINECITTA' Deluxe 8",
    ton: "7.1 & Dolby Atmos",
    leinwand: "ca. 34 m²",
    projektion: "Digital 4k",
    plaetze: 64,
    digital3D: true,
    image: "/assets/images/deluxe8.jpg",
  },
  {
    name: "CINECITTA' Deluxe 9",
    ton: "7.1 & Dolby Atmos",
    leinwand: "ca. 34 m²",
    projektion: "Digital 4k",
    plaetze: 64,
    digital3D: true,
    image: "/assets/images/deluxe9.jpg",
  },
  {
    name: "CINECITTA' Deluxe 10",
    ton: "7.1 & Dolby Atmos",
    leinwand: "ca. 96 m²",
    projektion: "Digital Laser 4k",
    plaetze: 162,
    digital3D: true,
    image: "/assets/images/deluxe10.jpg",
  },
  {
    name: "Studio-Kino 1",
    ton: "5.1 - Dirac Live",
    leinwand: "ca. 18 m²",
    projektion: "Digital 2k",
    plaetze: 33,
    digital3D: false,
    image: "/assets/images/studio1.jpg",
  },
  {
    name: "Studio-Kino 2",
    ton: "7.1 - Dirac Live",
    leinwand: "ca. 18 m²",
    projektion: "Digital 4k",
    plaetze: 47,
    digital3D: false,
    image: "/assets/images/studio2.jpg",
  },
  {
    name: "Studio-Kino 3",
    ton: "7.1 - Dirac Live",
    leinwand: "ca. 12 m²",
    projektion: "Digital 4k",
    plaetze: 43,
    digital3D: true,
    image: "/assets/images/studio3.jpg",
  },
  {
    name: "Open Air",
    ton: "5.0 - Dirac Live",
    leinwand: "ca. 24 m²",
    projektion: "Digital 2k",
    plaetze: 101,
    digital3D: false,
    image: "/assets/images/openair.jpg",
  },
];
